---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: "percygrunwald/docker-centos7-ansible:latest"
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  #env:
    #ANSIBLE_ROLES_PATH: ../../../roles/
verifier:
  name: ansible
